[package]
name = "cm7"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cortex-m = "0.7"
cortex-m-rt = "0.6"
stm32h7xx-hal = { version = "0.10", features = [ "stm32h747cm7" ] }
log = { version = "0.4", default-features = false }

